"""Step definitions for the unified-mode e2e features (LCORE-2343).

Covers configuration validation, legacy-to-unified migration, and run.yaml
synthesis for the five ``unified-mode-*.feature`` files.

Design rules (from the LCORE-2343 planning notes):

- Validation, migration, and synthesis steps operate on the **on-disk**
  configuration artifacts — never the live service. "The active
  configuration" is the repo-root ``lightspeed-stack.yaml`` copy that
  ``configure_service`` applied.
- Migration and synthesis run the real CLIs as subprocesses — exactly the
  surface the server entrypoint and operators use — and assertions parse
  the produced YAML (data equality, never byte comparison).
- The synthesis-log step is mode-aware: in server mode the synthesis
  evidence is emitted by the llama-stack container (entrypoint + CLI), not
  the lightspeed-stack container the Gherkin names; the scenario's intent
  (R10: the synthesized path is logged at startup) is asserted against the
  container that actually synthesizes.
"""

import difflib
import os
import re
import shutil
import stat
import subprocess
import sys
import tempfile
import time
from pathlib import Path
from typing import Any, Optional

import yaml
from behave import given, step, then, when  # pyright: ignore
from behave.runner import Context

# Generated by the --migrate-config step; matches the .gitignore entry.
MIGRATED_CONFIG_BASENAME = "lightspeed-stack-unified-migrated.yaml"
# Legacy half of "the legacy migration fixture pair"; its run.yaml half is
# the repo-root run.yaml the CI harness materializes.
MIGRATION_PAIR_LCS_BASENAME = "lightspeed-stack-legacy-for-migration.yaml"

CLI_TIMEOUT_SECONDS = 120
CUSTOM_OUTPUT_POLL_SECONDS = 60


def _mode_subdir(context: Context) -> str:
    """Return the mode fixture subdirectory name for the current harness mode."""
    return "library-mode" if context.is_library_mode else "server-mode"


def _config_dir(context: Context) -> Path:
    """Resolve the active fixture directory, mode subdir included when present.

    Mirrors ``configure_service``'s resolution so files referenced by name in
    Gherkin (fixture pairs, migrated output) land where that step finds them.
    """
    base = Path(
        getattr(context, "lightspeed_stack_config_directory", "")
        or "tests/e2e/configuration"
    )
    mode_base = base / _mode_subdir(context)
    return mode_base if mode_base.is_dir() else base


def _active_config_path() -> Path:
    """Return the on-disk active configuration (the applied repo-root copy)."""
    return Path("lightspeed-stack.yaml")


def _run_cli(
    args: list[str], cwd: Optional[Path] = None
) -> subprocess.CompletedProcess:
    """Run a repo CLI as a subprocess, capturing output, never raising."""
    return subprocess.run(
        [sys.executable, *args],
        cwd=str(cwd) if cwd else None,
        capture_output=True,
        text=True,
        timeout=CLI_TIMEOUT_SECONDS,
        check=False,
    )


def _load_yaml(path: Path) -> Any:
    """Parse a YAML file."""
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def _native_override(config_path: Path) -> dict[str, Any]:
    """Extract llama_stack.config.native_override from a config file."""
    config = _load_yaml(config_path)
    override = ((config.get("llama_stack") or {}).get("config") or {}).get(
        "native_override"
    )
    assert override, f"{config_path} carries no llama_stack.config.native_override"
    return override


def _synthesized(context: Context) -> Path:
    """Return the synthesized run.yaml path recorded by an earlier step."""
    path = getattr(context, "synthesized_run_yaml_path", None)
    assert path, "no synthesis step ran before this assertion"
    return Path(path)


# ---------------------------------------------------------------------------
# Validation (unified-mode-validation.feature)
# ---------------------------------------------------------------------------


@when("configuration validation is attempted for the active configuration")
def attempt_configuration_validation(context: Context) -> None:
    """Validate the on-disk active configuration via the service CLI.

    Runs ``lightspeed_stack.py --dump-configuration -c lightspeed-stack.yaml``
    as a black-box subprocess: ``main()`` loads (and thereby validates) the
    configuration before any dump handling, so a Pydantic validation failure
    surfaces on stderr with a non-zero exit code. cwd is the repo root so the
    invalid fixtures' ``library_client_config_path: run.yaml`` resolves to the
    harness-materialized run.yaml and the captured failure is the intended
    cross-field error, not a file-not-found.
    """
    result = _run_cli(
        [
            "src/lightspeed_stack.py",
            "--dump-configuration",
            "-c",
            str(_active_config_path()),
        ]
    )
    context.validation_returncode = result.returncode
    context.validation_output = result.stdout + result.stderr
    assert result.returncode != 0, (
        "expected the active configuration to fail validation, but the load "
        f"succeeded (rc=0). Output:\n{context.validation_output}"
    )


@then("the validation error contains {text}")
def validation_error_contains(context: Context, text: str) -> None:
    """Assert the captured validation failure mentions the given text."""
    output = getattr(context, "validation_output", None)
    assert output is not None, "no validation attempt ran before this assertion"
    assert (
        text.strip() in output
    ), f"validation error does not contain {text!r}. Full output:\n{output}"


# ---------------------------------------------------------------------------
# Migration (unified-mode-migration.feature)
# ---------------------------------------------------------------------------


@step("lightspeed-stack --migrate-config is run for the legacy migration fixture pair")
def run_migrate_config(context: Context) -> None:
    """Migrate the legacy fixture pair into the active fixture directory.

    The pair is ``lightspeed-stack-legacy-for-migration.yaml`` (mode subdir)
    plus the repo-root ``run.yaml`` the harness materializes. The output lands
    in the same mode subdir under the name later Gherkin steps reference, so
    ``configure_service`` can boot it; it is gitignored and cleaned up after
    the scenario.
    """
    pair_lcs = _config_dir(context) / MIGRATION_PAIR_LCS_BASENAME
    pair_run = Path("run.yaml")
    output = _config_dir(context) / MIGRATED_CONFIG_BASENAME
    assert pair_lcs.is_file(), f"missing migration fixture {pair_lcs}"
    assert pair_run.is_file(), "repo-root run.yaml (harness-materialized) missing"

    # Migrate into a scratch directory so the CLI's own artifact keeps the
    # mode it was written with and can be asserted on (R10) instead of being
    # relaxed in place.
    scratch = Path(tempfile.mkdtemp(prefix="lcore-e2e-migrate-"))
    context.add_cleanup(lambda: shutil.rmtree(scratch, ignore_errors=True))
    cli_output = scratch / MIGRATED_CONFIG_BASENAME

    result = _run_cli(
        [
            "src/lightspeed_stack.py",
            "--migrate-config",
            "--run-yaml",
            str(pair_run),
            "-c",
            str(pair_lcs),
            "--migrate-output",
            str(cli_output),
        ]
    )
    assert result.returncode == 0 and cli_output.is_file(), (
        f"--migrate-config failed (rc={result.returncode}).\n"
        f"stdout:\n{result.stdout}\nstderr:\n{result.stderr}"
    )
    # R10: migrated files may carry lifted secrets, so the CLI must write them
    # owner-only. Assert it here rather than silently relaxing the artifact.
    cli_mode = stat.S_IMODE(os.stat(cli_output).st_mode)
    assert cli_mode == 0o600, (
        f"--migrate-config wrote {cli_output} with mode {oct(cli_mode)}, "
        "expected 0o600 (R10)"
    )

    # configure_service boots a repo-root copy of this file, and the container
    # user cannot read a host-owned 0600 file. Publish a deliberate 0644 *copy*
    # into the fixture directory for the harness to boot; the CLI artifact
    # above keeps its 0600 mode. The fixture pair is env-reference-only by
    # design, so nothing secret is widened.
    shutil.copyfile(cli_output, output)
    os.chmod(output, 0o644)
    context.migrated_cli_output_path = cli_output
    context.migrated_config_path = output
    context.migration_pair_run_yaml = pair_run
    context.add_cleanup(lambda: output.unlink(missing_ok=True))


@then("the file {filename} contains {text}")
def file_contains(context: Context, filename: str, text: str) -> None:
    """Assert a file in the active fixture directory contains a substring."""
    path = _config_dir(context) / filename.strip()
    content = path.read_text(encoding="utf-8")
    assert text.strip() in content, f"{path} does not contain {text!r}"


@then("the file {filename} does not contain {text}")
def file_does_not_contain(context: Context, filename: str, text: str) -> None:
    """Assert a file in the active fixture directory lacks a substring."""
    path = _config_dir(context) / filename.strip()
    content = path.read_text(encoding="utf-8")
    assert text.strip() not in content, f"{path} unexpectedly contains {text!r}"


# ---------------------------------------------------------------------------
# Synthesis (unified-mode-synthesis.feature + migration round-trip)
# ---------------------------------------------------------------------------


@step("the active unified configuration is synthesized to run.yaml")
def synthesize_active_configuration(context: Context) -> None:
    """Synthesize a run.yaml from the on-disk unified configuration.

    Runs the config CLI exactly as the server entrypoint does (unified
    auto-detection dispatches to ``synthesize_to_file``, which also gives the
    0600 output mode). Source precedence: the migrated config when the
    migration step ran in this scenario, else the active on-disk config.
    When the custom-output service step ran instead, this step is a
    pass-through — the service subprocess performs the synthesis.
    """
    if getattr(context, "custom_output_path", None):
        return

    source = getattr(context, "migrated_config_path", None) or _active_config_path()
    scratch = Path(tempfile.mkdtemp(prefix="lcore-e2e-synthesis-"))
    context.add_cleanup(lambda: shutil.rmtree(scratch, ignore_errors=True))
    output = scratch / "run.yaml"

    result = _run_cli(
        ["src/llama_stack_configuration.py", "-c", str(source), "-o", str(output)]
    )
    assert result.returncode == 0 and output.is_file(), (
        f"synthesis CLI failed (rc={result.returncode}) for {source}.\n"
        f"stdout:\n{result.stdout}\nstderr:\n{result.stderr}"
    )
    context.synthesized_run_yaml_path = output


@then(
    "the synthesized run.yaml parses to the same data as the legacy migration fixture run.yaml"
)
def synthesized_round_trips(context: Context) -> None:
    """Assert migrate-then-synthesize reproduces the pair's run.yaml (data equality)."""
    synthesized = _load_yaml(_synthesized(context))
    original = _load_yaml(
        getattr(context, "migration_pair_run_yaml", None) or Path("run.yaml")
    )
    if synthesized != original:
        diff = "\n".join(
            difflib.unified_diff(
                yaml.dump(original, sort_keys=True).splitlines(),
                yaml.dump(synthesized, sort_keys=True).splitlines(),
                fromfile="pair run.yaml",
                tofile="synthesized",
                lineterm="",
            )
        )
        raise AssertionError(f"round-trip data mismatch:\n{diff}")


@then(
    "the synthesized run.yaml contains the native_override scalar value for safety.excluded_categories"
)
def synthesized_scalar_override(context: Context) -> None:
    """Assert the override's scalar replaced the baseline value at that key (R5)."""
    override_value = _native_override(_active_config_path())["safety"][
        "excluded_categories"
    ]
    synthesized = _load_yaml(_synthesized(context))
    actual = (synthesized.get("safety") or {}).get("excluded_categories")
    assert actual == override_value, (
        f"safety.excluded_categories is {actual!r}, expected the "
        f"native_override value {override_value!r}"
    )
    baseline = _load_yaml(Path("run.yaml"))
    baseline_value = (baseline.get("safety") or {}).get("excluded_categories")
    assert baseline_value != override_value, (
        "fixture and baseline agree on safety.excluded_categories — the "
        "replacement assertion would be vacuous"
    )


@then("the synthesized run.yaml contains exactly the native_override list for apis")
def synthesized_list_override(context: Context) -> None:
    """Assert the override list replaced the baseline's apis wholesale (R5)."""
    override_list = _native_override(_active_config_path())["apis"]
    synthesized = _load_yaml(_synthesized(context))
    assert (
        synthesized.get("apis") == override_list
    ), f"apis is {synthesized.get('apis')!r}, expected exactly {override_list!r}"
    baseline = _load_yaml(Path("run.yaml"))
    assert (
        baseline.get("apis") != override_list
    ), "fixture and baseline agree on apis — wholesale replacement would be vacuous"


@then("the synthesized run.yaml contains ${{env.OPENAI_API_KEY}}")
def synthesized_keeps_env_reference(context: Context) -> None:
    """Assert the emitted secret stays an environment reference on disk (R6)."""
    content = _synthesized(context).read_text(encoding="utf-8")
    assert (
        "${env.OPENAI_API_KEY}" in content
    ), "synthesized run.yaml does not carry the ${env.OPENAI_API_KEY} reference"


@then("the synthesized run.yaml does not contain the resolved OPENAI_API_KEY value")
def synthesized_no_literal_secret(context: Context) -> None:
    """Assert the literal secret value never lands on disk (R6)."""
    secret = os.environ.get("OPENAI_API_KEY", "")
    assert secret, (
        "OPENAI_API_KEY is not set in the harness environment — the "
        "no-literal-secret assertion would be vacuous"
    )
    content = _synthesized(context).read_text(encoding="utf-8")
    assert (
        secret not in content
    ), "synthesized run.yaml contains the resolved OPENAI_API_KEY value"


@then("the synthesized run.yaml file permissions are 0600")
def synthesized_permissions(context: Context) -> None:
    """Assert the synthesized file is owner-read/write only (R10)."""
    mode = stat.S_IMODE(os.stat(_synthesized(context)).st_mode)
    assert mode == 0o600, f"synthesized run.yaml mode is {oct(mode)}, expected 0o600"


# ---------------------------------------------------------------------------
# --synthesized-config-output (unified-mode-synthesis.feature)
# ---------------------------------------------------------------------------


@given(
    "lightspeed-stack is started with --synthesized-config-output set to a custom path"
)
def start_with_custom_synthesis_output(context: Context) -> None:
    """Launch a short-lived local service with a custom synthesis output path.

    The flag only affects library-mode in-process synthesis, and the running
    containers cannot be restarted with different CLI args — so this step
    always uses the library-mode variant of the active fixture, copied to a
    scratch directory with ``service.port`` rewritten to avoid clashing with
    the running stack. The subprocess synthesizes during app startup; the
    following Then steps poll for the file, and the process is killed on
    scenario cleanup.
    """
    active_basename = _active_config_path().name
    fixture_basename = Path(
        getattr(context, "feature_config", "")
        or "lightspeed-stack-unified-providers.yaml"
    ).name
    base = Path(
        getattr(context, "lightspeed_stack_config_directory", "")
        or "tests/e2e/configuration"
    )
    library_fixture = base / "library-mode" / fixture_basename
    if not library_fixture.is_file():
        library_fixture = _config_dir(context) / fixture_basename
    assert library_fixture.is_file(), f"no library-mode fixture for {active_basename}"

    scratch = Path(tempfile.mkdtemp(prefix="lcore-e2e-synthout-"))
    context.add_cleanup(lambda: shutil.rmtree(scratch, ignore_errors=True))

    config = _load_yaml(library_fixture)
    config.setdefault("service", {})["port"] = 8099
    scratch_config = scratch / "lightspeed-stack.yaml"
    with open(scratch_config, "w", encoding="utf-8") as f:
        yaml.safe_dump(config, f)

    custom_output = scratch / "custom-run.yaml"
    process = subprocess.Popen(  # pylint: disable=consider-using-with
        [
            sys.executable,
            str(Path("src/lightspeed_stack.py").resolve()),
            "-c",
            str(scratch_config),
            "--synthesized-config-output",
            str(custom_output),
        ],
        cwd=str(scratch),
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    )
    context.custom_output_path = custom_output
    context.custom_output_scratch = scratch
    context.custom_output_process = process

    def _kill() -> None:
        if process.poll() is None:
            process.kill()
            process.wait(timeout=10)

    context.add_cleanup(_kill)


@then("the synthesized run.yaml is written to the custom output path")
def custom_output_written(context: Context) -> None:
    """Poll for the custom-path synthesis output and validate it parses."""
    custom_output = Path(context.custom_output_path)
    process = context.custom_output_process
    deadline = time.monotonic() + CUSTOM_OUTPUT_POLL_SECONDS
    while time.monotonic() < deadline:
        if custom_output.is_file() and custom_output.stat().st_size > 0:
            break
        if process.poll() is not None and not custom_output.is_file():
            out = process.stdout.read() if process.stdout else ""
            raise AssertionError(
                f"service exited (rc={process.returncode}) before writing the "
                f"custom synthesis output.\n{out[-2000:]}"
            )
        time.sleep(0.5)
    assert custom_output.is_file(), (
        f"custom synthesis output {custom_output} did not appear within "
        f"{CUSTOM_OUTPUT_POLL_SECONDS}s"
    )
    assert isinstance(_load_yaml(custom_output), dict)
    context.synthesized_run_yaml_path = custom_output


@then("the default synthesized run.yaml path does not exist")
def default_output_absent(context: Context) -> None:
    """Assert the default synthesis location was not used (override took effect)."""
    scratch = Path(context.custom_output_scratch)
    default_path = scratch / ".generated" / "run.yaml"
    assert (
        not default_path.exists()
    ), f"default synthesis path {default_path} exists despite the override"


# ---------------------------------------------------------------------------
# Startup logging (unified-mode-synthesis.feature) — mode-aware, see module
# docstring and LCORE-2343 planning decision Q2.
# ---------------------------------------------------------------------------


@then("the lightspeed-stack container logs contain synthesized run.yaml")
def container_logs_show_synthesis(context: Context) -> None:
    """Assert the container that synthesizes logged the synthesized-config path.

    Library mode: the lightspeed-stack container itself synthesizes in-process
    and logs "Using synthesized OGX config at <path>". Server mode: synthesis
    happens in the llama-stack container (entrypoint + config CLI), which logs
    the generated-config path — the Gherkin names lightspeed-stack, but the
    scenario's intent (R10: the path is logged at startup) can only be observed
    on the synthesizing container. Deviation agreed in planning (Q2).

    The message text follows the OGX rename (PRs #2516/#2547): client.py logs
    "Using synthesized OGX config at %s" and llama_stack_configuration.py logs
    "Wrote synthesized OGX configuration to %s (mode 0600)".
    """
    if context.is_library_mode:
        container = "lightspeed-stack"
        pattern = r"Using synthesized OGX config|synthesized.*run\.yaml"
    else:
        container = "llama-stack"
        pattern = (
            r"Wrote synthesized OGX configuration"
            r"|Using generated config:.*run\.yaml"
            r"|mode auto-detected"
        )

    result = subprocess.run(
        ["docker", "logs", container],
        capture_output=True,
        text=True,
        timeout=60,
        check=False,
    )
    assert (
        result.returncode == 0
    ), f"docker logs {container} failed: {result.stderr[-500:]}"
    logs = result.stdout + result.stderr
    assert re.search(pattern, logs), (
        f"{container} logs carry no synthesis-path evidence "
        f"(pattern {pattern!r} not found)"
    )
