BUILDER_BASE_IMAGE=registry.redhat.io/rhai/base-image-cpu-rhel9:3.4.0-1777399554
BUILDER_DNF_COMMAND=dnf
RUNTIME_BASE_IMAGE=registry.redhat.io/rhai/base-image-cpu-rhel9:3.4.0-1777399554
RUNTIME_DNF_COMMAND=dnf
