name: Lightspeed Core Service (LCS)
service:
  host: 0.0.0.0
  port: 8080
  auth_enabled: false
  workers: 1
  color_log: true
  access_log: true
llama_stack:
  # Uses a remote llama-stack service
  # The instance would have already been started with a llama-stack-run.yaml file
  use_as_library_client: false
  # Alternative for "as library use"
  # use_as_library_client: true
  # library_client_config_path: <path-to-llama-stack-run.yaml-file>
  url: http://localhost:8321
  api_key: xyzzy
user_data_collection:
  feedback_enabled: true
  feedback_storage: "/tmp/ramdisk"
  transcripts_enabled: true
  transcripts_storage: "/tmp/ramdisk"

authentication:
  module: "noop"
conversation_cache:
  type: "postgres"
  postgres:
    host: 127.0.0.1
    db: test
    user: tester
    password: 123qwe
    ssl_mode: disable
    gss_encmode: disable

#byok_rag:
#  - rag_id: ocp_docs
#    rag_type: inline::faiss
#    embedding_dimension: 1024
#    vector_db_id: vector_byok_1
#    db_path: /tmp/ocp.faiss
#  - rag_id: knowledge_base
#    rag_type: inline::faiss
#    embedding_dimension: 384
#    vector_db_id: vector_byok_2
#    db_path: /tmp/kb.faiss

quota_handlers:
  sqlite:
      db_path: quota.sqlite
  limiters:
    - name: user_monthly_limits
      type: user_limiter
      initial_quota: 10
      quota_increase: 10
      period: "2 hours"
    - name: cluster_monthly_limits
      type: cluster_limiter
      initial_quota: 100
      quota_increase: 10
      period: "1 day"
  scheduler:
    # scheduler ticks in seconds
    period: 1
