name: Bandit security scanner

on:
  pull_request:
    branches:
      - main

jobs:
  bandit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: mdegis/bandit-action@v1.0
        with:
          path: "src"
          exit_zero: true
