name: Build image

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - name: Install podman
        run: |
          sudo apt-get update
          sudo apt-get -y install podman
      - name: Verify podman
        run: podman --version
      - name: Build image
        run: podman build -t lightspeed-stack:latest .

