name: Check dependencies

on:
  - push
  - pull_request

jobs:
  check_dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: uv sync
      - name: List dependencies
        run: uv pip list
