name: Integration tests

on:
  - push
  - pull_request

jobs:
  integration_tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Python version
        run: uv run python --version
      - name: uv version
        run: uv --version
      - name: Install dependencies
        run: uv pip install --python ${{ matrix.python-version }} -e .
      - name: Install pdm  # Required for dynamic version test
        run: uv pip install pdm
      - name: Run integration tests
        run: uv run pytest tests/integration --cov=src --cov=runner --cov-report term-missing
