name: Pydocstyle

on:
  - push
  - pull_request

jobs:
  pydocstyle:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.12'
      - name: Python linter
        run: uv tool run pydocstyle -v .
