name: Radon

on:
  pull_request:
    branches:
      - main

jobs:
  radon:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    name: "radon"
    steps:
      - uses: actions/checkout@v3
      - uses: davidslusser/actions_python_radon@v1.0.0
        with:
          src: "src"
          min: "A"
          grade: "B"
